export const ROUTES = {
  ROOT: '/',
  LOGIN: '/login',
  UNAUTHORIZED: '/unauthorized',
  DASHBOARD: '/dashboard',
  DATA_COLLECTION: '/data-collection',
  NEEDS: '/needs',
  VOLUNTEERS: '/volunteers',
  MAP: '/map',
  AI_MATCHING: '/ai-matching',
  NOTIFICATIONS: '/notifications',
  REPORTS: '/reports',
  SETTINGS: '/settings',
  HELP: '/help',

  VOLUNTEER_ROOT: '/volunteer',
  VOLUNTEER_DASHBOARD: '/volunteer/dashboard',
  VOLUNTEER_TASKS: '/volunteer/tasks',
  VOLUNTEER_DATA_COLLECTION: '/volunteer/data-collection',
  VOLUNTEER_MAP: '/volunteer/map',
  VOLUNTEER_EVENTS: '/volunteer/events',
  VOLUNTEER_FEED: '/volunteer/feed',
  VOLUNTEER_NOTIFICATIONS: '/volunteer/notifications',
  VOLUNTEER_PROFILE: '/volunteer/profile',

  COMMUNITY_ROOT: '/community',
  COMMUNITY_DASHBOARD: '/community/dashboard',
  COMMUNITY_REPORT: '/community/report',
  COMMUNITY_TRACKER: '/community/tracker',
  COMMUNITY_FEED: '/community/feed',
  COMMUNITY_SOS: '/community/sos',
  COMMUNITY_RESOURCES: '/community/resources',
  COMMUNITY_PROFILE: '/community/profile',
}
